# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180414_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategorybrand',
            old_name='cagegory',
            new_name='category',
        ),
    ]
